### ISSUE TITLE
Continuare proiect

### ISSUE THREAD

**Issue by Thomas1995** [dserban/StateMachineTestingWithQuickCheck#11]
Am o intrebare. Chiar daca CDL-ul este gata, e vreo sansa sa pot continua cu contributii la acest proiect?

**Comment by dserban** [comment]
@Thomas1995
Sigur ca da, dar cel mai probabil e nevoie sa stabilim un nou set de obiective.
Tu cand termini sesiunea de examene?

**Comment by Thomas1995** [comment]
@dserban 
Pe 10 iunie am primul examen, ultimul pe 27 iunie, iar de pe 1 iulie incep job-ul.

**Comment by dserban** [comment]
@Thomas1995
OK, atunci trimite-mi, te rog, un reminder dupa sesiune.
Nu sunt foarte sigur ca voi fi in tara in perioada aceea, dar vorbim si stabilim.

**Comment by Thomas1995** [comment]
Am terminat sesiunea!
