### ISSUE TITLE
QuickCheck probleme arbitrary

### ISSUE THREAD

**Issue by Thomas1995** [dserban/StateMachineTestingWithQuickCheck#12]
@dserban 

Am inceput sa lucrez la partea cu mongodb, insa aparent QuickCheck are niste probleme si nu inteleg care ar putea fi acestea. De exemplu, din urmatoarea secventa de cod:

```
instance Arbitrary CustomPostList where
 arbitrary = do
   size <- arbitrary
   list <- vectorOf (size `mod` maxCustomListSize + minCustomListSize) (arbitrary :: Gen CustomPost)
   return $ MkCustomPostList list
```

size este mereu 0

```
instance Arbitrary CustomPost where
 arbitrary = do
   value <- listOf1 genSafeChar
   return $ MkCustomPost $ ["value" =: value]
  where
   genSafeChar = elements $ ['a'..'z'] ++ ['A'..'Z'] ++ ['0'..'9']
```

Aici, in acelasi mod, listOf1 returneaza de fiecare data o secventa aleatorie de lungime 1 (de fiecare data, adica lungimea nu se schimba).

Nu inteleg care ar putea fi problema. Intregul cod [aici](https://github.com/Thomas1995/StateMachineTestingWithQuickCheck/blob/master/mongodb/mongo_big_insertions.hs).

**Comment by dserban** [comment]
@Thomas1995
Poti sa testezi cum arata cateva esantioane generate de `listOf1` cu functia `sample` in modul urmator:
```
λ> sample $ listOf1 $ elements $ ['a'..'z'] ++ ['A'..'Z'] ++ ['0'..'9']
"e"
"Id"
"7"
"m56j"
"NkgNzw"
"SBQhmU7"
"ijOUA"
"oSDcWTU7I"
"Xb"
"hvR"
"iX3lgBAUXCsR"
λ>
```
La mine observ ca lungimea variaza de la o invocare la alta, la tine cum se vede output-ul expresiei de mai sus?

**Comment by dserban** [comment]
@Thomas1995
Pentru partea cu size, incearca artificiul pe care l-am folosit si eu in exemplul cu "circular buffer", si anume:
```
actionListLength <- choose (1,50)
```

**Comment by Thomas1995** [comment]
@dserban 

Nu gasesc nicaieri functia sample.

```
<interactive>:2:1: Not in scope: `sample' 
```

**Comment by Thomas1995** [comment]
Vad ca asa merge...

```
"Y"
"Ih"
"wW"
"uC"
"MawDH"
"CVfp2S2aYv"
"fU77kuAf7x"
"LGyvV81tznfvbX"
"bH8RLVux"
"y6ZNFtZPXYaPgPu"
"d"

```

**Comment by dserban** [comment]
@Thomas1995
Daca vrei sa mai schimbam idei, putem vorbi pe Hangouts azi sau maine, si eventual sa-mi trimiti ecran sa vad pe concret cum se manifesta problemele.

**Comment by Thomas1995** [comment]
@dserban 
Maine ar fi perfect.
