### ISSUE TITLE
Sedinta 2 aprilie

### ISSUE THREAD

**Issue by Thomas1995** [dserban/StateMachineTestingWithQuickCheck#2]
Buna ziua, eu si Relu ne-am inscris la un hackathon de 24h care va fi sambata si duminica, prin urmare nu putem ajunge sambata, 2 aprilie. Ce putem face in acest sens?

**Comment by dserban** [comment]
@Thomas1995

E in regula, multumesc ca m-ai anuntat ca sa stiu sa nu vin.
Te rog sa iei legatura si cu organizatorii CDL, sa stie si ei.

Mersi,
-Dan
