### ISSUE TITLE
Am gasit bug-uri

### ISSUE THREAD

**Issue by Thomas1995** [dserban/StateMachineTestingWithQuickCheck#4]
Am reusit sa fac un cod care sa functioneze. La inceput am introdus eu niste bug-uri pentru a testa daca functioneaza si a gasit acele bug-uri.

Am scos apoi bug-urile introduse de mine si a gasit bug-uri in webdis / redis. Ce am facut a fost sa bag in baza de data perechi chei valoare, apoi cautam dupa cheie si comparam valorile sa vad daca sunt introduse corect. In modul ghci nu gaseste nimic, dar daca compilez cu ghc apoi rulez executabilul gaseste mereu destul de repede (< 200 testari).

Ce cred eu ca se intampla, desi nu sunt sigur, e ca ruland executabilul rezultat din ghc, se ruleaza programul mai rapid si atunci cand baza de date sau webdis-ul (nu stiu la care dintre ele e problema) e bombardata rapid cu multe query-uri apar bug-uri.

Ce pot face mai departe? Fac un Pull request cu codul? Postez un issue pe github-ul webdis?

**Comment by dserban** [comment]
@Thomas1995
Hai sa lasam asta pe sambata, o sa ma uit si eu la ce se intampla ca sa nu scapam din vedere ceva "obvious" si dupa aceea sa ne facem de ras.
