### ISSUE TITLE
Extragere din GET (Redis)

### ISSUE THREAD

**Issue by Thomas1995** [dserban/StateMachineTestingWithQuickCheck#5]
Continuare a discutiei de astazi: Cum extrang string-ul care ma intereseaza din output-ul pe care il ofera GET-ul?

**Comment by dserban** [comment]
@Thomas1995

Uite o metoda oarecum barbara / quick-and-dirty.

Mai intai de toate:
```
stack install MissingH
```
Apoi:
```
$ ghci
λ> import Database.Redis
λ> import Data.Either.Utils (fromRight)
λ> :set -XOverloadedStrings
λ> conn <- connect defaultConnectInfo
λ> runRedis conn $ get "zzz"
Right Nothing
λ> runRedis conn $ get "aaa"
Right (Just "bbb")
λ> resultOfTypeEither <- runRedis conn $ get "aaa"
λ> :t resultOfTypeEither
resultOfTypeEither
  :: Either Reply (Maybe Data.ByteString.Internal.ByteString)
λ> :t fromRight
fromRight :: Either a b -> b
λ> fromRight resultOfTypeEither
Just "bbb"
λ> :t fromRight resultOfTypeEither
fromRight resultOfTypeEither
  :: Maybe Data.ByteString.Internal.ByteString
```
Apoi valoarea de tip `Maybe` o tratezi cu fromJust.

Din nou, nu asta este "the point" atunci cand lucrezi cu valori de tip `Maybe` si `Either`, dar pentru experimente in GHCi, e OK.

**Comment by Thomas1995** [comment]
@dserban 

Programul merge acum. Am lasat un numar mare de teste sa ruleze si n-a gasit niciun bug. Il voi lasa mai mult, peste noapte probabil, iar daca nu merge ma voi gandi la alte metode de abordare.

Codul este pus pe github, pe fork-ul meu, tot in folderul redis.

**Comment by dserban** [comment]
@Thomas1995
Daca n-ai gasit bug-uri probabil ca e o idee buna sa incepi sa testezi functionalitati mai sofisticate din Redis, de exemplu sorted sets:
http://www.tutorialspoint.com/redis/redis_sorted_sets.htm
Sa te gandesti pana sambata viitoare cam cum ar arata un test pentru sorted sets si ce proprietati ai putea scrie care sa implice o lista de API calls de lungime arbitrara.
