### ISSUE TITLE
Sedinta sambata 14 mai

### ISSUE THREAD

**Issue by Thomas1995** [dserban/StateMachineTestingWithQuickCheck#8]
Facem sedinta de pe 14 mai?

**Comment by dserban** [comment]
@Thomas1995
Salut,
Da, voi fi prezent sambata la CDL, si am stabilit pentru vineri seara ca recuperam.
Vorbeste tu, te rog, si cu Relu sa venim cu totii vineri la 16:00 in hol EC sus, unde sunt mesele (langa peretele cu cantina).
-Dan

**Comment by Thomas1995** [comment]
Deci vineri si sambata. Am inteles. O sa il anunt.
